# -*- coding: utf-8 -*-
"""Derivative_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ln_gBINi8rfnlliF0J6GIPahV7YhkgTt
"""

def derivativeFunction(*numbers):
  d = ""
  pNomial = ""
  for i in range(0, len(numbers), 2):
    newCeo = numbers[i] * numbers[i + 1]
    newEx = numbers[i + 1] - 1
    c = str(newCeo)
    e = str(newEx)
    d += c + "x^" + e
    if i + 2 < len(numbers):
      d += " + "
    oldCeo = str(numbers[i])
    oldEx = str(numbers[i + 1])
    pNomial += oldCeo + "x^" + oldEx
    if i + 2 < len(numbers):
      pNomial += " + "
  print(f"d[{pNomial}]' = {d}")

polynomial = [5, 6, 3, 2]

derivativeFunction(*polynomial)